### ISSUE TITLE
2007 support?

### ISSUE THREAD

**Issue by greenship24** [browlry/SentFolderByFrom#2]
Much appreciated as this works on a 2010 install. I'm trying to configure it for a 2007 install though and didn't see documentation as to if it is supported (I could've missed it.)

I can verify it's installed, add-in is shown and enabled. Cannot seem to get it to prompt at all though when sending as delegate.
No userconfig.bin is ever placed. I've moved one (userconfig.bin) from another computer to this one and still cannot get it to work properly. Have uninstalled and reinstalled multiple times with no effect.

So in the end I'm just wondering if 2007 is supported. If it is, I'll at least know I have a configuration issue elsewhere in the program.
Thanks

**Comment by browlry** [comment]
Hello,

Thanks for trying out this add-in!

I'm surprised to hear it works in Outlook 2010, but that's cool.

I don't plan to add support for Office 2007.

If you don't mind compiling the program yourself, [this thread](https://stackoverflow.com/a/12284425/4463400) might be helpful.

To paraphrase:

1. Clone the repository using Git (`git clone https://github.com/browlry/SentFolderByFrom.git`).
2. Use a text editor to open `SentFolderByFrom\SentFolderByFrom.vbproj` and scroll to line 261.
3. Change the value of `DebugInfoExeName` 
    from
     `"#Software\Microsoft\Office\16.0\Outlook\InstallRoot\Path#outlook.exe"`
    to 
    `"#Software\Microsoft\Office\12.0\Outlook\InstallRoot\Path#outlook.exe"` (including the quotation marks).
4. Open `SentFolderByFrom.sln` in Visual Studio 2017.
5. Click the `Build` menu and select `Build Solution`.
6. Run `SentFolderByFrom\bin\Release\SentFolderByFrom.vsto` to install the add-in.
